name: iOS Build for AltStore
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build IPA
        run: flutter build ipa --no-codesign --release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BabelOn-V1 # <--- Changed name to avoid the "v3 conflict"
          path: build/ios/ipa/*.ipa
          overwrite: true # <--- Added this to prevent it from hanging
